# Generated by Django 4.0.2 on 2022-03-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btamplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(upload_to='company_logos')),
                ('Project_name', models.CharField(max_length=200)),
                ('Business_case_proposal_date', models.DateField(auto_now=True, null=True, verbose_name='')),
                ('sponsor', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=200)),
                ('internal_stakeholder', models.CharField(max_length=200)),
                ('external_stakeholder', models.CharField(max_length=200)),
                ('Need_for_the_project', models.CharField(max_length=200)),
                ('Alignment_with_Business_Priorities', models.CharField(max_length=200)),
                ('Proposed_Solution_or_Methodology', models.CharField(max_length=200)),
                ('Impacted_Business_Function_or_Area', models.CharField(max_length=200)),
                ('Indicative_Risk_Level_of_the_Project', models.CharField(max_length=200)),
                ('Proposed_Start_Date', models.DateField(auto_now=True, null=True, verbose_name='')),
                ('Overall_Project_Timeframe', models.DateField(auto_now=True, null=True, verbose_name='')),
                ('Estimated_completion_Date', models.DateField(auto_now=True, null=True, verbose_name='')),
                ('Location_of_Project_Implementation', models.CharField(max_length=200)),
                ('Approximate_costs_of_the_Project', models.CharField(max_length=200)),
                ('Estimate_Benefits_Financial_or_Non_Financial', models.CharField(max_length=200)),
                ('Impact_or_Risks_of_doing_nothing_Financial_or_Non_Financial', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
