# Generated by Django 4.0.2 on 2022-03-15 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('btamplate', '0002_form_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Business_case_proposal_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='form',
            name='Estimated_completion_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='form',
            name='Overall_Project_Timeframe',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='form',
            name='Proposed_Start_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
