# Generated by Django 4.0.2 on 2022-04-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btamplate', '0002_formi_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formi',
            name='logo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
