# Generated by Django 4.0.2 on 2022-03-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btamplate', '0002_createform_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='createform',
            table='createForm',
        ),
    ]
