# Generated by Django 4.0.2 on 2022-03-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btamplate', '0003_alter_createform_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='createform',
            table=None,
        ),
    ]
